test_record = {
    'gemeente': "'s-Gravenhage",
    'cbs gemeentecode': 'GM0518',
    'nummer stembureau': 517,
    'naam stembureau': 'Stadhuis',
    'gebruikersdoel het gebouw': 'Kantoor',
    'website locatie': 'https://www.denhaag.nl/nl/bestuur-en-organisatie/contact-met-de-gemeente/stadhuis-den-haag.htm',
    'wijknaam': 'Centrum',
    'cbs wijknummer': 'WK051828',
    'buurtnaam': 'Kortenbos',
    'cbs buurtnummer': 'BU05182811',
    'bag referentie nummer': '0518200000747446',
    'straatnaam': 'Spui',
    'huisnummer': 70,
    'huisletter': '',
    'huisnummertoevoeging': '',
    'postcode': '2511 BT',
    'plaats': 'Den Haag',
    'extra adresaanduiding': '',
    'x': '81611',
    'y': '454909',
    'longitude': '4.3166395',
    'latitude': '52.0775912',
    'openingstijden': '2019-03-20T07:30:00 tot 2019-03-20T21:00:00',
    'mindervaliden toegankelijk': 'Y',
    'akoestiek': 'N',
    'mindervalide toilet aanwezig': 'Y',
    'kieskring id': "'s-Gravenhage",
    'hoofdstembureau': '',
    'contactgegevens': 'Unit Verkiezingen, verkiezingen@denhaag.nl 070-3534488 Gemeente Den Haag Publiekszaken/Unit Verkiezingen Postbus 84008 2508 AA Den Haag',
    'beschikbaarheid': 'https://www.stembureausindenhaag.nl/',
    'verkiezingen': 'waterschapsverkiezingen voor Delfland',
    '1.1.a aanduiding aanwezig': 'Y',
    '1.1.b aanduiding duidelijk zichtbaar': 'Y',
    '1.1.c aanduiding goed leesbaar': 'Y',
    '1.2.a gpa aanwezig': 'N',
    '1.2.b aantal vrij parkeerplaatsen binnen 50m van de entree': 6,
    '1.2.c hoogteverschil tussen parkeren en trottoir': 'Y',
    '1.2.d hoogteverschil': 20,
    '1.2.e type overbrugging': 'Helling',
    '1.2.f overbrugging conform itstandaard': 'Y',
    '1.3.a vlak, verhard en vrij van obstakels': 'Y',
    '1.3.b hoogteverschil': 30,
    '1.3.c type overbrugging': 'Lift',
    '1.3.d overbrugging conform itstandaard': 'Y',
    '1.3.e obstakelvrije breedte van de route': 120,
    '1.3.f obstakelvrije hoogte van de route': 200,
    '1.4.a is er een route tussen gebouwentree en stemruimte': 'Y',
    '1.4.b route duidelijk aangegeven': 'Y',
    '1.4.c vlak en vrij van obstakels': 'Y',
    '1.4.d hoogteverschil': 10,
    '1.4.e type overbrugging': 'Helling',
    '1.4.f overbrugging conform itstandaard': 'Y',
    '1.4.g obstakelvrije breedte van de route': 110,
    '1.4.h obstakelvrije hoogte van de route': 220,
    '1.4.i deuren in route bedien- en bruikbaar': 'Y',
    '2.1.a deurtype': 'Handbediend',
    '2.1.b opstelruimte aan beide zijden van de deur': 'Y',
    '2.1.c bedieningskracht buitendeur': '<40N',
    '2.1.d drempelhoogte (t.o.v. straat/vloer niveau)': '<2cm',
    '2.1.e vrije doorgangsbreedte buitendeur': '>85cm',
    '2.2.a tussendeuren aanwezig in eventuele route': 'Y',
    '2.2.b deurtype': 'Handbediend',
    '2.2.c opstelruimte aan beide zijden van de deur': 'Y',
    '2.2.d bedieningskracht deuren': '<40N',
    '2.2.e drempelhoogte (t.o.v. vloer niveau)': '<2cm',
    '2.2.f vrije doorgangsbreedte deur': '>85cm',
    '2.3.a deur aanwezig naar/van stemruimte': 'Y',
    '2.3.b deurtype': 'Handbediend',
    '2.3.c opstelruimte aan beide zijden van de deur': 'Y',
    '2.3.d bedieningskracht deur': '<40N',
    '2.3.e drempelhoogte (t.o.v. vloer niveau)': '<2cm',
    '2.3.f vrije doorgangsbreedte deur': '>85cm',
    '2.4.a zijn er tijdelijke voorzieningen aangebracht': 'Y',
    '2.4.b vloerbedekking: randen over de volle lengte deugdelijk af': 'Y',
    '2.4.c hellingbaan: weerbestendig (alleen van toepassing bij bui': 'Y',
    '2.4.d hellingbaan: deugdelijk verankerd aan ondergrond': 'Y',
    '2.4.e leuning bij hellingbaan/trap: leuning aanwezig en conform': 'Y',
    '2.4.f dorpeloverbrugging: weerbestendig (alleen van toepassing ': 'Y',
    '2.4.g dorpeloverbrugging: deugdelijk verankerd aan ondergrond': 'Y',
    '3.1.a obstakelvrije doorgangen': 'Y',
    '3.1.b vrije draaicirkel / manoeuvreerruimte': 'Y',
    '3.1.c idem voor stemtafel en stemhokje': 'Y',
    '3.1.d opstelruimte voor/naast stembus': 'Y',
    '3.2.a stoelen in stemruimte aanwezig': 'Y',
    '3.2.b 1 op 5 stoelen uitgevoerd met armleuningen': 'Y',
    '3.3.a hoogte van het laagste schrijfblad': 60,
    '3.3.b schrijfblad onderrijdbaar': 'Y',
    '3.4.a hoogte inworpgleuf stembiljet': 70,
    '3.4.b afstand inwerpgleuf t.o.v. de opstelruimte': 160,
    '3.5.a leesloep (zichtbaar) aanwezig': 'Y',
    '3.6.a kandidatenlijst in stemlokaal aanwezig': 'Y',
    '3.6.b opstelruimte voor de kandidatenlijst aanwezig': 'Y'
}
