# NOTE: Development config (also make any relevant changes to
# Dockerfile-app)


FROM python:3.12
MAINTAINER Open State Foundation <developers@openstate.eu>

RUN echo "Europe/Amsterdam" > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales
RUN apt-get update && apt-get install -y gdal-bin unzip

RUN sed -i -e 's/# nl_NL.UTF-8 UTF-8/nl_NL.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales

WORKDIR /opt/stm
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

ENV FLASK_APP=website.py
ENV FLASK_DEBUG=1
CMD flask run --host=0.0.0.0 --extra-files="./static/dist/bundled/"
